/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Answer from "./script/scene/Answer"
import QueRuntime from "./script/runtime/QueRuntime"
import QueDialogUpdate from "./script/ui/QueDialogUpdate"
import GradeRuntime from "./script/runtime/GradeRuntime"
import GradeUpdate from "./script/ui/GradeUpdate"
import TimerRuntime from "./script/runtime/TimerRuntime"
import TimerUpdate from "./script/ui/TimerUpdate"
import AnsRuntime from "./script/runtime/AnsRuntime"
import CircleSpriteRuntime from "./script/runtime/CircleSpriteRuntime"
import AnsUpdate from "./script/ui/AnsUpdate"
import AnsHeadRuntime from "./script/runtime/AnsHeadRuntime"
import AnsHeadUpdate from "./script/ui/AnsHeadUpdate"
import Auth from "./script/scene/Auth"
import Finish from "./script/scene/Finish"
import Main from "./script/scene/Main"
import MatchRoom from "./script/scene/MatchRoom"
import LabelRuntime from "./script/runtime/LabelRuntime"
import VSRoom from "./script/scene/VSRoom"
import DialogRuntime from "./script/runtime/DialogRuntime"
import DialogUpdate from "./script/ui/DialogUpdate"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="VSRoom.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/scene/Answer.ts",Answer);
        reg("script/runtime/QueRuntime.ts",QueRuntime);
        reg("script/ui/QueDialogUpdate.ts",QueDialogUpdate);
        reg("script/runtime/GradeRuntime.ts",GradeRuntime);
        reg("script/ui/GradeUpdate.ts",GradeUpdate);
        reg("script/runtime/TimerRuntime.ts",TimerRuntime);
        reg("script/ui/TimerUpdate.ts",TimerUpdate);
        reg("script/runtime/AnsRuntime.ts",AnsRuntime);
        reg("script/runtime/CircleSpriteRuntime.ts",CircleSpriteRuntime);
        reg("script/ui/AnsUpdate.ts",AnsUpdate);
        reg("script/runtime/AnsHeadRuntime.ts",AnsHeadRuntime);
        reg("script/ui/AnsHeadUpdate.ts",AnsHeadUpdate);
        reg("script/scene/Auth.ts",Auth);
        reg("script/scene/Finish.ts",Finish);
        reg("script/scene/Main.ts",Main);
        reg("script/scene/MatchRoom.ts",MatchRoom);
        reg("script/runtime/LabelRuntime.ts",LabelRuntime);
        reg("script/scene/VSRoom.ts",VSRoom);
        reg("script/runtime/DialogRuntime.ts",DialogRuntime);
        reg("script/ui/DialogUpdate.ts",DialogUpdate);
    }
}
GameConfig.init();